@startuml

entity _app {
  + app.RootComponent
}

entity _splash {
  + splash.RootSplashComponent
  --
  # splash.splash.SplashActivityComponent
}

entity _tmdb {
  + tmdb.RootTmdbComponent
  --
  # tmdb.list.presentation.ListActivityComponent
  # tmdb.list.impl.InitializationContentProviderComponent
}

_app -down- _splash
_app -down- _tmdb

@enduml
